---
title: "Are Tennis Seeds Accurate?"
subtitle: "Michael Messmer's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

In tennis, "seeding" is the act of ensuring that the players who are most likely to win a tournament will not face each other early on. A player's seed is determined by their ranking as well as their recent performance. In an algorithmically ideal world, a higher seeded player should always beat a lower seeded player. This is obviously not the case in the real world, as the seeding system cannot not account for all variables, like favorable matchups or whether or not a player is having a bad day. But just how accurate is the seeding system? That is what this project will attempt to find out.

It is important to note that the lower the numeric value of the seed is, the higher the seed is. For example, a 3 seeded player is expected to beat a 7 seeded player. So although the numeric value we are assigning is greater than the official seeds, this actually means that they will be treated as a lower seed, which means they would be expected to lose to an officially seeded player. The semantics of the analysis and the way that seeds are referred to will follow these 2 rules:

1. The higher seeded player is expected to beat the lower seeded player.
2. The player with a smaller numerical seed is expected to beat the player with the greater numerical seed.

### 1. Discovery and Data Preparation

The first deliverable collects our data and massages it into usable form, as well as trimming away data that we don't need. It also provides visualizations that give extra insight into our data and answer our initial questions.

<a href="deliverable1.html">Discovery and Data Preparation</a>

### 2. Model Planning and Building

The second deliverable builds off of the data from our first deliverable, supplementing it with extra data and building a model to predict the total amount of points won by the winner of a match.

<a href="deliverable2.html">Model Planning and Building</a>

### 3. Results and Operationalization

Coming soon...

